apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-alerting-rules
  namespace: observability
  labels:
    loki_rule: custom
data:
  rules.yaml: |
    groups:
      - name: test_alert
        rules:
          - alert: TestAlert
            expr: sum(rate({app="loki"} | logfmt | level="info"[1m])) by (container) > 0
            for: 1m
            labels:
              severity: warning
            annotations:
              summary: Loki2 info warning per minute rate > 0

  rules2.yaml: |
    groups:
      - name: test_alert2
        rules:
          - alert: TestAlert2
            expr: sum(rate({app="loki"} | logfmt | level="dd"[1m])) by (container) > 0
            for: 1m
            labels:
                severity: warning
            annotations:
              summary: Loki2 info warning per minute rate > 0
