apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: probes-rules
  labels:
    resource: prom-custom
spec:
  groups:
  - name: probes-rules
    rules:
    - alert: Readiness-probe-Failure
      annotations:
        timestamp: >
          time: {{ with query "time()" }}{{ . | first | value | humanizeTimestamp }}{{ end }}
        description: Readiness probe is failing.
      expr: |
        (prober_probe_total{probe_type="Readiness",result="failed", container=~"^nc-.*", service="prometheus-kube-prometheus-kubelet"} offset 1m) != prober_probe_total{probe_type="Readiness",result="failed", container=~"^nc-.*", service="prometheus-kube-prometheus-kubelet"}
      for: 10s
      labels:
        severity: warning
      # readiness probe failure


    - alert: Liveness-Probe-Failure-Or-container-restart
      annotations:
        timestamp: >
          time: {{ with query "time()" }}{{ . | first | value | humanizeTimestamp }}{{ end }}
        description: Liveness probe failure or Container restart occurred in last 2 min.
      expr: |
        sum(increase(kube_pod_container_status_restarts_total{container=~"^nc-.*"}[2m])) by (pod, container) > 0
      for: 10s
      labels:
        severity: warning
      # Liveness probe or container restart failure